{"name": "test_fixture_zcc3[cc_calculator_shuju0]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 6\n  +1\n  -6", "trace": "self = <cc_work.test_fixture_zcc.TestCal_cc_new object at 0x00000000039B4BE0>, cc_calculator_func = <cc_work.calculator_cc.Calculator object at 0x00000000039B4470>, cc_calculator_shuju = [3, 2, 6]\n\n    @pytest.mark.run(order=2)\n    def test_fixture_zcc3(self, cc_calculator_func, cc_calculator_shuju):\n        result = cc_calculator_func.sub(cc_calculator_shuju[0], cc_calculator_shuju[1])\n        print('这是测试用例3')\n        # print(result)\n>       assert result == cc_calculator_shuju[2]\nE       assert 1 == 6\nE         +1\nE         -6\n\ntest_fixture_zcc.py:39: AssertionError"}, "parameters": [{"name": "cc_calculator_shuju", "value": "[3, 2, 6]"}], "start": 1609398357932, "stop": 1609398357933, "uuid": "34e3cb3b-0dcf-4ab9-9cad-4619384c2b39", "historyId": "55d4b31f85bfc8d80350c229ae9c5eb0", "testCaseId": "2d0d19b682c0cb341a030c07193f3dc7", "fullName": "test_fixture_zcc.TestCal_cc_new#test_fixture_zcc3", "labels": [{"name": "suite", "value": "test_fixture_zcc"}, {"name": "subSuite", "value": "TestCal_cc_new"}, {"name": "host", "value": "admin-PC"}, {"name": "thread", "value": "12680-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fixture_zcc"}]}