{"name": "test_fixture_zcc4[cc_calculator_shuju1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == -3\n  +2\n  --3", "trace": "self = <cc_work.test_fixture_zcc.TestCal_cc_new object at 0x00000000039B4080>, cc_calculator_func = <cc_work.calculator_cc.Calculator object at 0x00000000039ABB00>, cc_calculator_shuju = [-1, -2, -3]\n\n    @pytest.mark.run(order=3)\n    def test_fixture_zcc4(self, cc_calculator_func, cc_calculator_shuju):\n        result = cc_calculator_func.mul(cc_calculator_shuju[0], cc_calculator_shuju[1])\n        print('这是测试用例4')\n        # print(result)\n>       assert result == cc_calculator_shuju[2]\nE       assert 2 == -3\nE         +2\nE         --3\n\ntest_fixture_zcc.py:46: AssertionError"}, "parameters": [{"name": "cc_calculator_shuju", "value": "[-1, -2, -3]"}], "start": 1609398358017, "stop": 1609398358018, "uuid": "9d89cc63-939e-4bc7-9368-92bb812eda97", "historyId": "7a399b3856c25c8cd2d75873bd3e80f9", "testCaseId": "000433c5f8a90c3b0946db3d61bfc89d", "fullName": "test_fixture_zcc.TestCal_cc_new#test_fixture_zcc4", "labels": [{"name": "suite", "value": "test_fixture_zcc"}, {"name": "subSuite", "value": "TestCal_cc_new"}, {"name": "host", "value": "admin-PC"}, {"name": "thread", "value": "12680-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fixture_zcc"}]}