{"name": "test_fixture_zcc3[cc_calculator_shuju1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == -3\n  +1\n  --3", "trace": "self = <cc_work.test_fixture_zcc.TestCal_cc_new object at 0x00000000039E1860>, cc_calculator_func = <cc_work.calculator_cc.Calculator object at 0x00000000039E1DD8>, cc_calculator_shuju = [-1, -2, -3]\n\n    @pytest.mark.run(order=2)\n    def test_fixture_zcc3(self, cc_calculator_func, cc_calculator_shuju):\n        result = cc_calculator_func.sub(cc_calculator_shuju[0], cc_calculator_shuju[1])\n        print('这是测试用例3')\n        # print(result)\n>       assert result == cc_calculator_shuju[2]\nE       assert 1 == -3\nE         +1\nE         --3\n\ntest_fixture_zcc.py:39: AssertionError"}, "parameters": [{"name": "cc_calculator_shuju", "value": "[-1, -2, -3]"}], "start": 1609398357943, "stop": 1609398357943, "uuid": "47b9027f-89d1-492a-ac4e-12e9ba0f8281", "historyId": "e013ed91007f28bbaba2c7a6176e3734", "testCaseId": "2d0d19b682c0cb341a030c07193f3dc7", "fullName": "test_fixture_zcc.TestCal_cc_new#test_fixture_zcc3", "labels": [{"name": "suite", "value": "test_fixture_zcc"}, {"name": "subSuite", "value": "TestCal_cc_new"}, {"name": "host", "value": "admin-PC"}, {"name": "thread", "value": "12680-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fixture_zcc"}]}