{"name": "test_fixture_zcc3[cc_calculator_shuju2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0 == 2000\n  +0\n  -2000", "trace": "self = <cc_work.test_fixture_zcc.TestCal_cc_new object at 0x00000000039AB390>, cc_calculator_func = <cc_work.calculator_cc.Calculator object at 0x00000000039AB9E8>, cc_calculator_shuju = [1000, 1000, 2000]\n\n    @pytest.mark.run(order=2)\n    def test_fixture_zcc3(self, cc_calculator_func, cc_calculator_shuju):\n        result = cc_calculator_func.sub(cc_calculator_shuju[0], cc_calculator_shuju[1])\n        print('这是测试用例3')\n        # print(result)\n>       assert result == cc_calculator_shuju[2]\nE       assert 0 == 2000\nE         +0\nE         -2000\n\ntest_fixture_zcc.py:39: AssertionError"}, "parameters": [{"name": "cc_calculator_shuju", "value": "[1000, 1000, 2000]"}], "start": 1609398357954, "stop": 1609398357954, "uuid": "3fb81aac-9396-41b4-ab90-ae259da6c53a", "historyId": "e50edcaa08206bcd301c8fb6f0e40fa9", "testCaseId": "2d0d19b682c0cb341a030c07193f3dc7", "fullName": "test_fixture_zcc.TestCal_cc_new#test_fixture_zcc3", "labels": [{"name": "suite", "value": "test_fixture_zcc"}, {"name": "subSuite", "value": "TestCal_cc_new"}, {"name": "host", "value": "admin-PC"}, {"name": "thread", "value": "12680-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fixture_zcc"}]}