{"name": "test_fixture_zcc[cc_calculator_shuju4]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 6 == 2\n  +6\n  -2", "trace": "self = <cc_work.test_fixture_zcc.TestCal_cc_new object at 0x000000000395DA58>, cc_calculator_func = <cc_work.calculator_cc.Calculator object at 0x00000000039AB438>, cc_calculator_shuju = [4, 2, 2]\n\n    @pytest.mark.run(order=1)\n    def test_fixture_zcc(self, cc_calculator_func, cc_calculator_shuju):\n        try:\n            result = cc_calculator_func.add(cc_calculator_shuju[0], cc_calculator_shuju[1])\n            print('这是测试用例1')\n            print(f'实际值为{result}')\n            print(f'预期值为{cc_calculator_shuju[2]}')\n            # assert result == cc_calculator_shuju[2]  写在else里才能断言成功\n        except Exception as e:\n            print(e)\n        else:\n>           assert result == cc_calculator_shuju[2]\nE           assert 6 == 2\nE             +6\nE             -2\n\ntest_fixture_zcc.py:25: AssertionError"}, "parameters": [{"name": "cc_calculator_shuju", "value": "[4, 2, 2]"}], "start": 1609398357905, "stop": 1609398357905, "uuid": "756e0244-d4c5-413b-bf54-3d6e303e6faa", "historyId": "b749b9a3caee8b30c243c2d85b79aba7", "testCaseId": "53c508109c33f2121310f004fb063ffe", "fullName": "test_fixture_zcc.TestCal_cc_new#test_fixture_zcc", "labels": [{"name": "suite", "value": "test_fixture_zcc"}, {"name": "subSuite", "value": "TestCal_cc_new"}, {"name": "host", "value": "admin-PC"}, {"name": "thread", "value": "12680-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fixture_zcc"}]}